# -*- coding: utf-8 -*-
"""ETL_Bovespa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xs7PQgoKt3I7h3aUuvWCbcp2YAQ-roaD
"""

import pandas as pd

def read_file(path, filename, year_date, type_file):
  _file = f'{path}{filename}{year_date}.{type_file}' 

  # Mapear colunas
  colspecs = [(2,10),
              (10,12),
              (12,24),
              (27,39),
              (56,69),
              (69,82),
              (82,95),
              (108,121),
              (152,170),
              (170,188)
  ]

  names = ['data_pregao', 
          'cod_bdi', 
          'sigla_acao', 
          'nome_acao', 
          'preco_abertura', 
          'preco_max', 
          'preco_min',
          'preco_fechamento',
          'qtd_negocios',
          'volume_negocios']

  df = pd.read_fwf(_file, colspecs=colspecs, names=names, skiprows=1)
  
  return df

# Filtrar ações
def filter_stocks(df):
  df = df [df['cod_bdi']==2]
  df = df.drop(['cod_bdi'], 1)
  
  return df

# Ajuste campo de data
def parse_date(df):
  df['data_pregao'] = pd.to_datetime(df['data_pregao'], format='%Y%m%d')
  
  return df

# Ajuste dos campos numéricos
def parse_values(df):
  df['preco_abertura'] = (df['preco_abertura']/100).astype(float)
  df['preco_max'] = (df['preco_max']/100).astype(float)
  df['preco_min'] = (df['preco_min']/100).astype(float)
  df['preco_fechamento'] = (df['preco_fechamento']/100).astype(float)
  
  return df

# Junção dos arquivos
def concat_files(path, filename, year_date, type_file, final_file):
  for i, y in enumerate(year_date):
    df = read_file(path, filename, y, type_file)
    df = filter_stocks(df)
    df = parse_date(df)
    df = parse_values(df)

    if i==0:
      df_final = df
    else:
      df_final = pd.concat([df_final, df])
  
  df_final.to_csv(f'{path}//{final_file}', index=False)

# Execução do script de ETL

year_date=['2021']

path=f'/content/'

filename='COTAHIST_A'

type_file='TXT'

final_file='all_bovespa.csv'

concat_files(path, filename, year_date, type_file, final_file)